# ========== DOSYA: learner/pyproject.toml ==========
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "azuraforge-learner"
version = "0.1.0"
authors = [{ name = "Azmi Sahin" }]
description = "High-level deep learning library for model training and management, using the AzuraForge Core engine."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "azuraforge-core @ git+https://github.com/AzuraForge/core.git",
    "scikit-learn", "matplotlib", "pandas", "pyarrow", "requests", 
    "python-dotenv", "PyYAML", "python-dateutil", "seaborn"
]

[tool.setuptools.packages.find]
where = ["src"]