[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "azuraforge-learner"
version = "0.1.2" # Sürüm artırımı
authors = [{ name = "Azmi Sahin" }]
description = "High-level deep learning library for model training and management, using the AzuraForge Core engine."
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
dependencies = [
    "azuraforge-core @ git+https://github.com/AzuraForge/core.git@main",
    "scikit-learn",
    "numpy",
    "redis",
    "matplotlib", # YENİ BAĞIMLILIK
    "pandas"      # YENİ BAĞIMLILIK (raporlama için)
]

[project.optional-dependencies]
dev = ["pytest"]